aggSubs: https://raw.githubusercontent.com/qjlxg/tor/refs/heads/main/data/subscribes.txt
subscriptions:
- https://raw.githubusercontent.com/qjlxg/tor/refs/heads/main/all_clash.txt
- https://raw.githubusercontent.com/qjlxg/skywrt/refs/heads/main/list_raw.txt

